apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app-deployment
  labels:
    app: streamlit-app
spec:
  replicas: 
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: vm27/streamlit-app:latest
        ports:
        - containerPort: 80

